
FIND_PATH (BOOST_SYSTEM_INCLUDE_DIRS boost/system/config.hpp PATHS ${BOOST_SYSTEM_INCLUDE_SEARCH} PATH_SUFFIXES boost)
FIND_LIBRARY (BOOST_SYSTEM_LIBRARIES boost_system PATHS ${BOOST_SYSTEM_LIBRARIES_SEARCH} PATH_SUFFIXES boost)
MESSAGE(STATUS "BOOST_SYSTEM INCLUDE DIRS = ${BOOST_SYSTEM_INCLUDE_DIRS}")
MESSAGE(STATUS "BOOST_SYSTEM LIBRARIES = ${BOOST_SYSTEM_LIBRARIES}")

INCLUDE (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (BOOST_SYSTEM DEFAULT_MSG BOOST_SYSTEM_LIBRARIES BOOST_SYSTEM_INCLUDE_DIRS)
